# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Hello. I'm Braden Desman."
my-name: "Braden Desman"
email: 'jzf5hc@virginia.edu'
description: "I'm an aspiring hardware engineer from Clifton, Virginia"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bradendesman.github.io" # the base hostname & protocol for your site, e.g. https://example.com
twitter_username: ''
github_username: ''
medium_username: ''

# Build settings
markdown: kramdown

kramdown:
   math_engine: mathjax
# theme: phantom # Uncomment once published to RubyGems
plugins:
  - jekyll-paginate
  - jekyll-pdf-embed

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set

paginate: 50
paginate_path: "/page/:num"


############################################################

### Phantom settings
footer_text: ''
admin_name: 'Braden Desman'
google_analytics: "" # Update with your own tracking ID
enable_contact: false

#### Phantom Navigation menu
enable_nav: true
nav_item:
  - { url: '/', text: 'Projects' }
  - { url: '/resume', text: 'Resume' }
  - { url: '/about', text: 'About' }
  
